on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        # Create the SSH key file with the private key from secrets
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add the server's host key to the known_hosts file
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Application
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          echo "Connected to remote server: $(hostname)"
          echo "Running deployment script on remote server..."

          # Navigate to the working directory
          cd ${{ secrets.WORK_DIR }

          # Handle Git updates
          git stash || true
          git checkout ${{ secrets.MAIN_BRANCH }}
          git pull origin ${{ secrets.MAIN_BRANCH }}
          
          # Copy environment variables
          cp ../.env ./backend
          cd /home/ubuntu/performanceAnalyzer/backend
          # Ensure Node.js and PM2 are available
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 22

          # Install dependencies
          cd backend
          npm install

          # Restart the application using PM2
          pm2 restart analyzerBackend
        EOF
